### ISSUE TITLE
MonoDevelop 5.0 Support

### ISSUE THREAD

**Issue by Mailaender** [AshleighAdams/LuaBinding#5]
An update for the @MonoDevelop 5.0 repository would be great. http://addins.monodevelop.com/Project/Index/98

**Comment by Mailaender** [comment]
Taking care of that myself then. https://github.com/monodevelop/LuaBinding/pull/1

**Comment by AshleighAdams** [comment]
@Mailaender I can transfer the repo over to you if you wish, and point the addin at http://addins.monodevelop.com/ to yours?

**Comment by Mailaender** [comment]
That may be a good idea. I am having a lot of trouble setting up the addin repository. https://github.com/slluis/cydin/issues/6
